---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ubuntu/xenial64
    memory: 1024
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
provisioner:
  name: ansible
  options:
    vvv: True
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
