---
# tasks file for kube-controller-manager
- name: Downloading Kubernetes {{K8_VER}} Packages - Controller Manager
  become: yes
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{K8_VER}}/bin/linux/amd64/kube-controller-manager
    dest: /usr/local/bin
    mode: '0777'

- name: Copying the kube-controller-manager-csr file to /opt/certs
  become: yes
  template:
    src: kube-controller-manager-csr.json.j2
    dest: /opt/certs/kube-controller-manager-csr.json

- name: Generating the Kube-Controller-Manager Keys
  become: yes
  shell: cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager && chmod 755 *
  args:
    chdir: /opt/certs

- name: Generating the Kube-Controller-Manager Config - Set Cluster
  become: yes
  shell: kubectl config set-cluster {{ K8_CLUSTER_NAME }} --certificate-authority=/opt/certs/ca.pem --embed-certs=true --server=https://{{ ansible_enp0s8.ipv4.address }}:6443 --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: /opt/configs

- name: Generating the Kube-Controller-Manager Config - Set Credentials
  become: yes
  shell: kubectl config set-credentials system:kube-controller-manager --client-certificate=/opt/certs/kube-controller-manager.pem --client-key=/opt/certs/kube-controller-manager-key.pem  --embed-certs=true --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: /opt/configs

- name: Generating the Kube-Controller-Manager Config - Set Context
  become: yes
  shell: kubectl config set-context default --cluster={{ K8_CLUSTER_NAME }} --user=system:kube-controller-manager  --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: /opt/configs

- name: Generating the Kube-Controller-Manager Config - Use Context
  become: yes
  shell: kubectl config use-context default --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: /opt/configs

- name: Copying the kube-controller-manager.service file to /etc/systemd/system
  become: yes
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
  notify: Start Kube-Controller-Manager